### ISSUE TITLE
angular 2 don't generate empty <target/> when extracting xlif

### ISSUE THREAD

**Issue by MSakamaki** [fourcube/omnixlf#2]
### problem

reading xlf without <target /> results in an error.
https://github.com/angular/angular/pull/18072

### desired action

xlf where <target /> does not exist will not result in an error.

It is necessary to modify the target extraction processing of `src/app/model.ts` as correspondence.

**Comment by fourcube** [comment]
Thank you for your contribution! I've just merged your PR.
