### ISSUE TITLE
error occurs if there is no attribute in <target>.

### ISSUE THREAD

**Issue by MSakamaki** [fourcube/omnixlf#4]
### problem

An error occurs if there is no attribute in <target>.

#### sucess xlf code

```xml
<source> souce message </source>
<target state = "new"> target message </target>

```

#### error xlf code

```xml
<source> souce message </source>
<target> target message </target>

```

### cause

When target is acquired with `_mapXliffTransUnitToTranslationUnit` method of `src/app/model.ts`, it seems that if there is no attribute in element, it becomes a character string type and becomes an error.

### desired action

The <target> element without attribute also needs to work properly

**Comment by fourcube** [comment]
Thank you!
